#!/bin/bash

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SECSI Email Command-line Script I v0.1.0
# Copyright 2014 Gary S. Weaver

if [ -z ${1+x} ]; then
    echo "
SECSI Email Command-line Script I
v0.0.1
Copyright 2014 Gary S. Weaver

usage:

  export IMAP_SERVER=imap.example.com:993
  export IMAP_USER=youremail@example.com
  ./secsi LIST '\"\" \"%\"'
  IMAP_MAILBOX=INBOX ./secsi FETCH 3456 FULL
  IMAP_MAILBOX=INBOX ./secsi FETCH 3456:3466 \"(BODY.PEEK[HEADER.FIELDS (DATE FROM SUBJECT)])\"
  IMAP_MAILBOX=INBOX ./secsi SEARCH SENTON 1-jun-2012
  IMAP_MAILBOX=INBOX ./secsi SEARCH SENTSINCE 1-may-2012 SENTBEFORE 3-jun-2012
"
    exit 1
fi

echo
if [ -z ${IMAP_SERVER+x} ]; then
    echo "set IMAP_SERVER, e.g. export IMAP_SERVER=imap.example.com:993"
    exit 1
else
    echo "IMAP_SERVER='$IMAP_SERVER'"
fi

if [ -z ${IMAP_USER+x} ]; then
    echo "set IMAP_USER, e.g. export IMAP_USER=youremail@example.com"
    exit 1
else
    echo "IMAP_USER='$IMAP_USER'"
fi

if [ -z ${IMAP_S_CLIENT_OPTS+x} ]; then
    # for starttls: IMAP_S_CLIENT_OPTS="-crlf -starttls smtp"
    export IMAP_S_CLIENT_OPTS="-crlf"
fi
echo "IMAP_S_CLIENT_OPTS='IMAP_S_CLIENT_OPTS'"

echo -n Password: 
read -s password
echo

IFS=' ' read -a split_s_client_opts <<< "$IMAP_S_CLIENT_OPTS"
echo "sending commands to: openssl s_client -connect $IMAP_SERVER $IMAP_S_CLIENT_OPTS"

(\
    echo "t1 LOGIN $IMAP_USER $password"
    test "$IMAP_MAILBOX" != '' && echo "t2 SELECT $IMAP_MAILBOX"
    echo "t3 ${*:1}"
    while sleep 1; do
        echo "t4 LOGOUT"
    done
) | openssl s_client -connect $IMAP_SERVER $split_s_client_opts
