#!/bin/bash

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SECSI Email Command-line Script I
# Copyright 2014 Gary S. Weaver

echo
if [ -z ${IMAP_SERVER+x} ]; then
    echo "set IMAP_SERVER, e.g. IMAP_SERVER=imap.example.com:993"
    exit 1
else
    echo "IMAP_SERVER='$IMAP_SERVER'"
fi

if [ -z ${IMAP_USER+x} ]; then
    echo "set IMAP_USER, e.g. IMAP_USER=youremail@example.com"
    exit 1
else
    echo "IMAP_USER='$IMAP_USER'"
fi

if [ -z ${1+x} ]; then
    echo "
SECSI Email Command-line Script I
v0.0.1
Copyright 2014 Gary S. Weaver

usage:

  secsi list
  secsi get mailbox id_or_range
    e.g.
    secsi get INBOX 3456
    secsi get INBOX 3456:3466
  secsi search mailbox search_string
    e.g
    secsi search INBOX SENTON 1-jun-2012
    secsi search INBOX SENTSINCE 1-may-2012 SENTBEFORE 3-jun-2012
  secsi expunge INBOX
"
    exit 1
fi

if [ -z ${IMAP_DELAY+x} ]; then
    export IMAP_DELAY=2
fi

echo -n Password: 
read -s password
echo

case $1 in
    list)
    (\
        sleep $IMAP_DELAY && \
        echo "t1 LOGIN $IMAP_USER $password" && \
        sleep $IMAP_DELAY && \
        echo "t2 LIST \"\" \"%\"" && \
        sleep $IMAP_DELAY && \
        echo "QUIT" ) | openssl s_client -connect $IMAP_SERVER -crlf
    ;;
    get)
    if [ -z ${3+x} ]; then
        echo "usage: secsi get mailbox id_or_range"
        exit 1
    fi
    echo "mailbox: $2"
    echo "id_or_range: $3"
    (\
        sleep $IMAP_DELAY && \
        echo "t1 LOGIN $IMAP_USER $password" && \
        sleep $IMAP_DELAY && \
        echo "t2 SELECT $2" && \
        sleep $IMAP_DELAY && \
        echo "t3 FETCH $3 FULL" && \
        sleep $IMAP_DELAY && \
        echo "QUIT" ) | openssl s_client -connect $IMAP_SERVER -crlf
    ;;
    search)
    if [ -z ${3+x} ]; then
        echo "usage: secsi search mailbox ..."
        exit 1
    fi
    echo "mailbox: $2"
    echo "search_string: ${*:3}"
    (\
        sleep $IMAP_DELAY && \
        echo "t1 LOGIN $IMAP_USER $password" && \
        sleep $IMAP_DELAY && \
        echo "t2 SELECT $2" && \
        sleep $IMAP_DELAY && \
        echo "t3 SEARCH ${*:3}" && \
        sleep $IMAP_DELAY && \
        echo "QUIT" ) | openssl s_client -connect $IMAP_SERVER -crlf
    ;;
    expunge)
    if [ -z ${2+x} ]; then
        echo "usage: secsi expunge mailbox"
        exit 1
    fi
    echo "mailbox: $2"
    (\
        sleep $IMAP_DELAY && \
        echo "t1 LOGIN $IMAP_USER $password" && \
        sleep $IMAP_DELAY && \
        echo "t2 SELECT $2" && \
        sleep $IMAP_DELAY && \
        echo "t3 EXPUNGE" && \
        sleep $IMAP_DELAY && \
        echo "QUIT" ) | openssl s_client -connect $IMAP_SERVER -crlf
    ;;
    *)
        echo "unsupported option: $1"
    ;;
esac
